---
use_cache: False # Use cache
followup_prob: 0.9 # Probabilty coverage of follow-up
z_min_b: 0.01 # Minimum redshift for background
z_max_b: 1.0 # Maximum redshift for background
frac_det: 1.0 # Fraction of flares detected
dt_followup: 200.0 # Length of follow-up campaign in days
gwmapdir: "/hildafs/projects/phy220048p/share/skymaps"

# AGN distribution
agn_distribution:
  model: "ConstantPhysicalDensity"
  args:
    - 1.77827941004e-5 # 10**-4.75 AGN/Mpc^3
  kwargs: {}
  density_args: []
  density_kwargs: {}

# Flare rate
flare_rate:
  model: "Kimura20"
  args: []
  kwargs: {}
  distribution:
    type: "normal"
    kwargs:
      scale: 0

# MCMC parameters
lambda0: 0.2 # Initial lambda for MCMC
H00: 70.0 # Initial H0 for MCMC
Om0: 0.3 # Initial Omega_m for MCMC
nwalkers: 32 # Number of walkers
nsteps: 5000 # Number of steps
nproc: 32 # Number of processes
