#!/bin/bash
#SBATCH -N 1
#SBATCH -n 32
#SBATCH -t 24:00:00
#SBATCH -J Posterior_inference_lambda_O3 
#SBATCH -o %x.log
#SBATCH -A phy220048p
#SBATCH -p HENON
#SBATCH --mail-type=ALL

### SETUP ###

# Print commands
set -x

# Print date
date

# Modules
module purge
module load anaconda3/2020.07

# Conda
source /opt/packages/anaconda3/etc/profile.d/conda.sh
conda deactivate
condaDIR="/hildafs/projects/phy200025p/tcabrera/.conda/envs/bbhagn"
conda activate $condaDIR

scriptPATH="/hildafs/projects/phy220048p/tcabrera/bbhagn/bbhagn/Posterior_inference_lambda_O3/Posterior_inference_lambda_O3.py"
configPATH="/hildafs/projects/phy220048p/tcabrera/bbhagn/bbhagn/Posterior_inference_lambda_O3/config.yaml"

### RUN JOB ###

# Call script
time python -u $scriptPATH $configPATH
